### ISSUE TITLE
переписать с psycopg2 на psycopg

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/xl2pg#1]
subj

Connecting to cubpure
Traceback (most recent call last):
  File "D:\home\mrcs\Dropbox\data\Scopus\master_list\2022-07\xl2pg-main\xl2pg.py", line 66, in <module>
    with psycopg.connect(dbname=db.dbname, user=db.user, password=db.password) as conn:
  File "C:\Users\mrcs\anaconda3\lib\site-packages\psycopg\connection.py", line 578, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: password authentication failed for user "mrcs"

**Comment by snorkysnark** [comment]
Обновил, правда не стало интерактивного ввода параметров подключения, т.к. я беру просто все аргументы из json'a
```python
psycopg.connect(**dbconfig)
```
