### ISSUE TITLE
error NotRequired

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/xl2pg#3]
Traceback (most recent call last):
  File "D:\home\mrcs\Dropbox\data\Scopus\master_list\2022-07\tmp\xl2pg\xl2pg.py", line 7, in <module>
    from typing_extensions import NotRequired
ImportError: cannot import name 'NotRequired' from 'typing_extensions' (C:\Users\mrcs\anaconda3\lib\site-packages\typing_extensions.py)

модуль стоит

(base) D:\home\mrcs\Dropbox\data\Scopus\master_list\2022-07\tmp\xl2pg>pip install typing_extensions
Requirement already satisfied: typing_extensions in c:\users\mrcs\anaconda3\lib\site-packages (3.10.0.2)

**Comment by snorkysnark** [comment]
Скорее всего, версия не та.
Сделай `pip install --upgrade typing_extensions`

**Comment by snorkysnark** [comment]
Если не выйдет обновить, могу убрать зависимость
Это type-hint'ы, которые используются в IDE, но не нужны для работы кода

**Comment by MarcusAkoev** [comment]
теперь пишет текст ниже. Откуда там JSON не понял

raceback (most recent call last):
  File "D:\home\mrcs\Dropbox\data\Scopus\master_list\2022-07\tmp\xl2pg\xl2pg.py", line 97, in <module>
    conninfo = json.loads(args.db.read_text())
  File "C:\Users\mrcs\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mrcs\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mrcs\anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 3 (char 72)

**Comment by snorkysnark** [comment]
Что-то не так в конфигурации БД (db.json)

**Comment by MarcusAkoev** [comment]
нашел, забыл запятую поставить
